# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/main/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

release:
  name_template: "{{ .Tag }}"

changelog:
  use: github  # use PR titles / commit messages
  sort: asc
