name: Test

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**.go'
      - '**.mod'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with: { go-version: stable }

    - name: Collect coverage
      run: make test_cover

    - uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage.out
        report: true
        chart: true
        amend: false
